lwcrecipies-master/force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

lwcrecipies-master/force-app/main/default/objects/Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Shipping Invoice</label>
    <referenceTo>Shipping_Invoice__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

lwcrecipies-master/force-app/main/default/classes/ItemController.cls
public with sharing class ItemController {

    @AuraEnabled
    public static String createItems( String itemRecords, String invoiceId ) {
        List<Item__c> items = (List<Item__c>)JSON.deserialize(itemRecords, List<Item__c>.class);
        for ( Integer i=0; i < items.size(); i ++) {
            items.get(i).Invoice__c = invoiceId;
        }
        List<Database.saveResult> saveResults = Database.insert(items, true);
        for ( Integer j=0; j< saveResults.size(); j++) {
            Database.saveResult sr = saveResults.get(j);
            if (sr.isSuccess()) {
                System.debug(System.LoggingLevel.DEBUG, 'Record Created!');
            }
        }
        return JSON.serialize(saveResults);
    }

    @AuraEnabled
    public static Decimal productPrice(String productId){
        List<PricebookEntry> pbEntryList = [SELECT Name, Product2.Name,PriceBook2.Name, UnitPrice 
                                                   FROM PricebookEntry 
                                                   Where IsActive = true
                                                   AND Product2Id =: productId
                                            ];
        Decimal price = 0.00;
        if (pbEntryList != null && pbEntryList.size() > 0) {
            price = pbEntryList.get(0).UnitPrice;
        }
        return price;
    }
}